sudo: required
language: node_js
cache:
  yarn: true
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
    - master
services:
  - docker
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV="test"
    - DEBUG="lorem:*"
node_js:
  - "8"
  - "6"
before_script:
  - make docker-start
  - make docker-stop # we test the docker-stop and docker-restart with this calls
  - make docker-restart
script:
  - make test-coveralls
after_script:
  - make docker-stop # after the tests we can test the docker-flush call
  - make docker-flush
