sudo: required
language: node_js
cache:
  yarn: true
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
    - master
services:
  - docker
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV="test"
    - DEBUG="lorem:*"
node_js:
  - "8"
  - "6"
before_script:
  - cd ./dockers && docker-compose up -d --build && cd -
script:
  - make test-coveralls
