version: '2.2'
services:
  couchbase:
    build: ./couchbase
    container_name: lorem_couchbase
    ports:
      - '8091-8094:8091-8094'
      - '11207:11207'
      - '11210:11210'
      - '18091-18093:18091-18093'
    healthcheck:
      test:
        - CMD
        - couchbase-cli
        - server-info
        - '--cluster=couchbase:8091'
        - '--user=Administrator'
        - '--password=password'
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - default.env
    networks:
      - lorem
  couchbase_init:
    build: ./couchbase
    container_name: lorem_couchbase_init
    command: /usr/local/bin/couchbase-init.sh
    depends_on:
      couchbase:
        condition: service_healthy
    links:
      - 'couchbase:couchbase'
    env_file:
      - default.env
    networks:
      - lorem
networks:
  lorem: null
